language: go
go:
  - "1.13.x"
  - "1.14.x"
sudo: false
install:
  - go get -d -t -v ./...
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
